apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bookstore
spec:
  template:
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/bookstore-project-464717/bookstore/bookstore-backend:dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bookstore
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: us-central1-docker.pkg.dev/bookstore-project-464717/bookstore/bookstore-frontend:dev
